# This is the "Blue" deployment
# It will be deployed first, or as the "old" version
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: myapp-container
        # This image tag will be replaced by the Jenkins pipeline
        image: rohhxn/myapp-bluegreen:__IMAGE_TAG__
        ports:
        - containerPort: 8080
        env:
        - name: APP_VERSION
          # This version string will be replaced by the Jenkins pipeline
          value: "__VERSION__ (Blue) 🔵"
        - name: BACKGROUND_COLOR
          value: "deepskyblue"
        # Liveness probe to check if the app is healthy
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

